#!/usr/bin/env bash
# write a bash script that displays information about subdomains.
domain_conf () {
    record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $record" | awk '{print "The subdomain "$1" is a "$2" record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
domain_conf "$1" "www"
domain_conf "$1" "lb-01"
domain_conf "$1" "web-01"
domain_conf "$1" "web-02"
elif [ "$#" -eq 2 ]; then
domain_conf "$1" "$2"
fi
