#!/usr/bin/env bash
# This script transfers the file from client to server
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
# Assigning arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
# Transfering the file from client to server
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
