#!/usr/bin/env bash
# This script transfers the file from client to server
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
    exit 1
fi
# Assigning arguments to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3

# Transfering the file from client to server
scp -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "File transfer failed"
fi
