#!/usr/bin/env bash
install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install haproxy -y

# Backup HAproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Edit HAproxy configuration
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
defaults
    log global
    option httplog
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
frontend http_front
    bind *:80
    mode http
    default_backend web-servers
backend web-servers
    balance roundrobin
    http-request add-header X-Served-By %[hostname]
    server web-01 100.26.168.254:80 check
    server web-02 100.26.246.144:80 check
EOF

# Restart HAproxy
sudo service haproxy restart
