#!/usr/bin/env bash
# Install and configure HAProxy on lb-01

sudo apt-get update -y
sudo apt-get install haproxy -y

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat << EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 4096
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    mode http
    default_backend backend_servers

backend backend_servers
    balance roundrobin
    mode http
    http-request add-header X-Served-By %[hostname]
    server web-01 647543-web-01 100.26.168.254:80 check
    server web-02 647543-web-02 100.26.246.144:80 check
EOF

sudo systemctl restart haproxy
sudo systemctl enable haproxy
